# Generated by Django 5.2.14 on 2026-05-07 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(verbose_name='日期')),
                ('steps', models.PositiveIntegerField(blank=True, null=True, verbose_name='步数')),
                ('exercise_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='运动时长')),
                ('average_heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='平均心率')),
                ('max_heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='最高心率')),
                ('min_heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='最低心率')),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='睡眠时长')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_health', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'record_date')},
            },
        ),
    ]
