# Generated by Django 5.2.14 on 2026-05-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpatient',
            name='grouping_batch',
        ),
        migrations.DeleteModel(
            name='GroupingBatch',
        ),
    ]
