# Generated by Django 5.2.14 on 2026-05-12 05:08

from django.db import migrations
from django.db.models import Q


def delete_unconfirmed_project_patients(apps, schema_editor):
    ProjectPatient = apps.get_model("studies", "ProjectPatient")
    Prescription = apps.get_model("prescriptions", "Prescription")
    CrfExport = apps.get_model("crf", "CrfExport")

    stale_project_patients = ProjectPatient.objects.filter(
        Q(group_id__isnull=True) | ~Q(grouping_status="confirmed")
    )
    stale_project_patient_ids = list(stale_project_patients.values_list("id", flat=True))
    if not stale_project_patient_ids:
        return

    Prescription.objects.filter(project_patient_id__in=stale_project_patient_ids).exclude(
        status="terminated"
    ).update(status="terminated")
    CrfExport.objects.filter(project_patient_id__in=stale_project_patient_ids).delete()
    ProjectPatient.objects.filter(id__in=stale_project_patient_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_remove_projectpatient_grouping_batch_and_more'),
        ('prescriptions', '0002_prescription_project_patient_set_null'),
        ('crf', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            delete_unconfirmed_project_patients,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='projectpatient',
            name='grouping_status',
        ),
    ]
