# Generated by Django 5.2.14 on 2026-05-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_remove_projectpatient_grouping_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpatient',
            name='grouping_status',
        ),
    ]
