# Generated by Django 5.2.14 on 2026-05-12 05:08

from django.db import migrations


def delete_unconfirmed_project_patients(apps, schema_editor):
    ProjectPatient = apps.get_model("studies", "ProjectPatient")
    ProjectPatient.objects.exclude(grouping_status="confirmed").delete()
    ProjectPatient.objects.filter(group_id__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_remove_projectpatient_grouping_batch_and_more'),
    ]

    operations = [
        migrations.RunPython(
            delete_unconfirmed_project_patients,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='projectpatient',
            name='grouping_status',
        ),
    ]
