# Generated by Django 5.2.16 on 2026-07-24 03:26

from django.db import migrations, models


def backfill_archived_project_completed_at(apps, schema_editor):
    StudyProject = apps.get_model("studies", "StudyProject")
    StudyProject.objects.filter(status="archived", completed_at__isnull=True).update(
        completed_at=models.F("updated_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_remove_projectpatient_grouping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyproject',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='项目完结时间'),
        ),
        migrations.RunPython(
            backfill_archived_project_completed_at,
            migrations.RunPython.noop,
        ),
    ]
