# Generated by Django 5.2.14 on 2026-05-07 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0001_initial'),
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_date', models.DateField(verbose_name='训练日期')),
                ('status', models.CharField(choices=[('completed', '已完成'), ('partial', '部分完成'), ('missed', '未完成')], max_length=20, verbose_name='完成状态')),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='实际时长')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='得分')),
                ('form_data', models.JSONField(default=dict, verbose_name='分类表单数据')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescriptions.prescription')),
                ('prescription_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescriptions.prescriptionaction')),
                ('project_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='studies.projectpatient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
