# Generated by Django 5.2.16 on 2026-07-10 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0011_prune_unofficial_action_library_items'),
        ('studies', '0003_remove_projectpatient_grouping_status'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_backend', models.CharField(default='qiniu_kodo', max_length=40, verbose_name='存储后端')),
                ('bucket', models.CharField(max_length=120, verbose_name='空间')),
                ('object_key', models.CharField(max_length=500, unique=True, verbose_name='对象 Key')),
                ('object_hash', models.CharField(blank=True, max_length=120, verbose_name='对象 Hash')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('content_type', models.CharField(max_length=120, verbose_name='文件类型')),
                ('size_bytes', models.PositiveBigIntegerField(verbose_name='文件大小')),
                ('duration_seconds', models.PositiveIntegerField(verbose_name='视频时长')),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('uploaded', '已上传'), ('attached', '已绑定'), ('failed', '失败'), ('expired', '已过期')], default='uploading', max_length=20, verbose_name='状态')),
                ('upload_token_expires_at', models.DateTimeField(verbose_name='上传凭证过期时间')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='上传完成时间')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescriptions.prescription')),
                ('prescription_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescriptions.prescriptionaction')),
                ('project_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_video_uploads', to='studies.projectpatient')),
                ('training_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to='training.trainingrecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotionAnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '待分析'), ('running', '分析中'), ('succeeded', '分析成功'), ('failed', '分析失败')], default='pending', max_length=20, verbose_name='状态')),
                ('algorithm_name', models.CharField(default='pp-tiny-pose', max_length=80, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(blank=True, max_length=80, verbose_name='算法版本')),
                ('rule_version', models.CharField(default='shoulder-press-v1', max_length=80, verbose_name='规则版本')),
                ('total_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='总次数')),
                ('standard_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='标准次数')),
                ('nonstandard_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='不标准次数')),
                ('result_payload', models.JSONField(default=dict, verbose_name='分析结果')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('prescription_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescriptions.prescriptionaction')),
                ('project_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.projectpatient')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_motion_analysis_jobs', to=settings.AUTH_USER_MODEL)),
                ('training_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motion_analysis_jobs', to='training.trainingrecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('training_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='training.trainingvideo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
