# Generated by Django 5.2.16 on 2026-07-10 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0011_prune_unofficial_action_library_items'),
        ('studies', '0003_remove_projectpatient_grouping_status'),
        ('training', '0002_training_video_analysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='motionanalysisjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('training_video',), name='unique_active_motion_analysis_job_per_video'),
        ),
    ]
