# Generated by Django 5.2.14 on 2026-07-14 11:32

import apps.training.video_models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingvideo_motionanalysisjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingvideo',
            name='upload_token_expires_at',
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='processing_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理过期时间'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='recording_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='录制结束时间'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='segment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='分片总数'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='uploaded_segment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='已上传分片数'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='content_type',
            field=models.CharField(default='video/mp4', max_length=120, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='视频时长'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='size_bytes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='status',
            field=models.CharField(choices=[('recording', '录制中'), ('uploading', '上传中'), ('queued', '待处理'), ('validating_segments', '校验分片'), ('merging', '合并中'), ('verifying_merge', '校验合并结果'), ('uploading_qiniu', '上传七牛'), ('verifying_qiniu', '校验七牛对象'), ('cleaning', '清理临时文件'), ('attached', '已绑定'), ('processing_failed', '处理失败'), ('expired', '已过期')], default='recording', max_length=32, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='VideoProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', '待处理'), ('validating_segments', '校验分片'), ('merging', '合并中'), ('verifying_merge', '校验合并结果'), ('uploading_qiniu', '上传七牛'), ('verifying_qiniu', '校验七牛对象'), ('cleaning', '清理临时文件'), ('succeeded', '处理成功'), ('failed', '处理失败'), ('expired', '已过期')], default='queued', max_length=32, verbose_name='状态')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='处理进度')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='处理尝试次数')),
                ('max_attempts', models.PositiveIntegerField(default=apps.training.video_models.processing_max_attempts_default, verbose_name='最大处理尝试次数')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='下次重试时间')),
                ('current_stage', models.CharField(blank=True, max_length=32, verbose_name='当前阶段')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('expires_at', models.DateTimeField(default=apps.training.video_models.processing_expiry_default, verbose_name='过期时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('training_video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_job', to='training.trainingvideo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingVideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_index', models.PositiveIntegerField(verbose_name='分片序号')),
                ('status', models.CharField(choices=[('pending', '待写入'), ('uploaded', '已上传'), ('failed', '失败')], default='uploaded', max_length=20, verbose_name='状态')),
                ('server_file_path', models.CharField(max_length=500, verbose_name='服务端临时文件')),
                ('content_type', models.CharField(default='video/mp4', max_length=120, verbose_name='文件类型')),
                ('size_bytes', models.PositiveBigIntegerField(verbose_name='文件大小')),
                ('duration_seconds', models.PositiveIntegerField(verbose_name='分片时长')),
                ('object_hash', models.CharField(max_length=64, verbose_name='文件 SHA-256')),
                ('upload_attempts', models.PositiveIntegerField(default=1, verbose_name='上传尝试次数')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传完成时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('training_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='training.trainingvideo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence_index', 'id'],
                'constraints': [models.UniqueConstraint(fields=('training_video', 'sequence_index'), name='uniq_training_video_segment_sequence')],
            },
        ),
    ]
