# Generated by Django 5.2.14 on 2026-07-10 16:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_client_session_ids(apps, schema_editor):
    TrainingVideo = apps.get_model("training", "TrainingVideo")
    for video in TrainingVideo.objects.filter(client_session_id__isnull=True).iterator():
        video.client_session_id = uuid.uuid4()
        video.save(update_fields=["client_session_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0011_prune_unofficial_action_library_items'),
        ('studies', '0003_remove_projectpatient_grouping_status'),
        ('training', '0003_unique_active_motion_analysis_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingVideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(verbose_name='分段序号')),
                ('duration_ms', models.PositiveIntegerField(verbose_name='分段时长毫秒')),
                ('size_bytes', models.PositiveBigIntegerField(verbose_name='分段大小')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('relative_path', models.CharField(blank=True, max_length=500, verbose_name='临时相对路径')),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('uploaded', '已上传'), ('deleted', '已删除'), ('failed', '失败')], default='uploading', max_length=20, verbose_name='状态')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='上传完成时间')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAssemblyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '处理中'), ('succeeded', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('output_relative_path', models.CharField(blank=True, max_length=500, verbose_name='输出相对路径')),
                ('qiniu_object_key', models.CharField(blank=True, max_length=500, verbose_name='七牛对象 Key')),
                ('qiniu_object_hash', models.CharField(blank=True, max_length=120, verbose_name='七牛对象 Hash')),
                ('cleanup_status', models.CharField(choices=[('pending', '待清理'), ('succeeded', '清理成功'), ('failed', '清理失败')], default='pending', max_length=20, verbose_name='清理状态')),
                ('cleanup_attempt_count', models.PositiveIntegerField(default=0, verbose_name='清理尝试次数')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('cleanup_error', models.TextField(blank=True, verbose_name='清理失败原因')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='心跳时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='actual_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='实际时长'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='client_session_id',
            field=models.UUIDField(null=True, verbose_name='客户端会话 ID'),
        ),
        migrations.RunPython(populate_client_session_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='trainingvideo',
            name='client_session_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='客户端会话 ID'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='expected_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='计划时长'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='expected_segment_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='计划分段数'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交完成时间'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='note',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='training_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='训练日期'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='uploaded_segment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='已上传分段数'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='bucket',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='空间'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='content_type',
            field=models.CharField(default='video/mp4', max_length=120, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='视频时长'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='object_key',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='对象 Key'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='size_bytes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='status',
            field=models.CharField(choices=[('uploading', '上传中'), ('uploaded', '已上传'), ('recording', '录制中'), ('uploading_segments', '分段上传中'), ('queued', '等待合并'), ('assembling', '合并中'), ('uploading_qiniu', '上传七牛中'), ('attached', '已绑定'), ('failed', '失败'), ('expired', '已过期')], default='uploading', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='upload_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上传凭证过期时间'),
        ),
        migrations.AddConstraint(
            model_name='trainingvideo',
            constraint=models.UniqueConstraint(fields=('project_patient', 'client_session_id'), name='unique_training_video_client_session_per_patient'),
        ),
        migrations.AddField(
            model_name='trainingvideosegment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingvideosegment',
            name='training_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='training.trainingvideo'),
        ),
        migrations.AddField(
            model_name='trainingvideosegment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoassemblyjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoassemblyjob',
            name='training_video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_job', to='training.trainingvideo'),
        ),
        migrations.AddField(
            model_name='videoassemblyjob',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='trainingvideosegment',
            constraint=models.UniqueConstraint(fields=('training_video', 'index'), name='unique_training_video_segment_index'),
        ),
    ]
