# Generated by Django 5.2.14 on 2026-07-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_trainingvideo_upload_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingvideo',
            name='training_date',
            field=models.DateField(blank=True, null=True, verbose_name='训练日期'),
        ),
    ]
