# Generated by Django 5.2.14 on 2026-07-11 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_remove_projectpatient_grouping_status'),
        ('training', '0005_remove_direct_video_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingvideo',
            name='cleanup_attempt_count',
            field=models.PositiveIntegerField(default=0, verbose_name='解绑清理尝试次数'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='cleanup_error',
            field=models.TextField(blank=True, verbose_name='解绑清理失败原因'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='cleanup_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解绑清理心跳时间'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='cleanup_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解绑清理请求时间'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='cleanup_status',
            field=models.CharField(blank=True, choices=[('', '无需清理'), ('pending', '待清理'), ('running', '清理中'), ('failed', '清理失败')], default='', max_length=20, verbose_name='解绑清理状态'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='project_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_video_uploads', to='studies.projectpatient'),
        ),
    ]
