# Generated by Django 5.2.16 on 2026-07-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_trainingvideo_cleanup_attempt_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoassemblyjob',
            name='qiniu_upload_deadline_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='七牛上传截止时间'),
        ),
    ]
