# Generated by Django 5.2.14 on 2026-07-11 10:41

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_existing_qiniu_cleanup_tombstones(apps, schema_editor):
    TrainingVideo = apps.get_model('training', 'TrainingVideo')
    VideoAssemblyJob = apps.get_model('training', 'VideoAssemblyJob')
    QiniuCleanupTombstone = apps.get_model('training', 'QiniuCleanupTombstone')

    jobs = {
        job.training_video_id: job
        for job in VideoAssemblyJob.objects.all().iterator()
    }
    for video in TrainingVideo.objects.all().iterator():
        job = jobs.get(video.id)
        attempt_count = job.attempt_count if job is not None else 0
        job_key = job.qiniu_object_key if job is not None else ''
        object_key = video.object_key or ''
        if attempt_count == 0 and not job_key and not object_key:
            continue

        prefix = f'training-videos/attempts/{video.id}-{video.client_session_id}/attempt-'
        if job is not None and job_key.startswith(prefix):
            job.qiniu_attempt_object_key = job_key
            job.save(update_fields=['qiniu_attempt_object_key'])

        canonical_key = object_key or ('' if job_key.startswith(prefix) else job_key)
        if video.status == 'attached' and object_key:
            canonical_key = object_key
        QiniuCleanupTombstone.objects.update_or_create(
            attempt_key_prefix=prefix,
            defaults={
                'session_id': video.client_session_id,
                'bucket': video.bucket or settings.QINIU_BUCKET,
                'max_attempt_number': attempt_count,
                'canonical_key': canonical_key,
                'retain_canonical': (
                    video.project_patient_id is not None
                    and video.cleanup_requested_at is None
                    and video.status != 'expired'
                ),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_videoassemblyjob_qiniu_upload_deadline_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='QiniuCleanupTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField(db_index=True, verbose_name='视频会话 UUID')),
                ('bucket', models.CharField(max_length=120, verbose_name='七牛空间')),
                ('attempt_key_prefix', models.CharField(max_length=500, unique=True, verbose_name='上传尝试 Key 前缀')),
                ('max_attempt_number', models.PositiveIntegerField(default=0, verbose_name='最大上传尝试序号')),
                ('canonical_key', models.CharField(blank=True, max_length=500, verbose_name='最终对象 Key')),
                ('retain_canonical', models.BooleanField(default=False, verbose_name='保留最终对象')),
                ('next_check_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='下次检查时间')),
                ('backoff_seconds', models.PositiveIntegerField(default=300, verbose_name='检查退避秒数')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最近检查时间')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='最近发现对象时间')),
                ('last_error', models.TextField(blank=True, verbose_name='最近清理错误')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='管理员归档时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='videoassemblyjob',
            name='qiniu_attempt_object_key',
            field=models.CharField(blank=True, max_length=500, verbose_name='七牛上传尝试对象 Key'),
        ),
        migrations.RunPython(
            seed_existing_qiniu_cleanup_tombstones,
            migrations.RunPython.noop,
        ),
    ]
