# Generated by Django 5.2.16 on 2026-08-04 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0011_prune_unofficial_action_library_items'),
        ('studies', '0004_studyproject_completed_at'),
        ('training', '0008_retire_legacy_training_pipeline_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QiniuCleanupTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField(db_index=True, verbose_name='视频会话 UUID')),
                ('bucket', models.CharField(max_length=120, verbose_name='七牛空间')),
                ('attempt_key_prefix', models.CharField(max_length=500, unique=True, verbose_name='上传尝试 Key 前缀')),
                ('max_attempt_number', models.PositiveIntegerField(default=0, verbose_name='最大上传尝试序号')),
                ('canonical_key', models.CharField(blank=True, max_length=500, verbose_name='最终对象 Key')),
                ('retain_canonical', models.BooleanField(default=False, verbose_name='保留最终对象')),
                ('next_check_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='下次检查时间')),
                ('backoff_seconds', models.PositiveIntegerField(default=300, verbose_name='检查退避秒数')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最近检查时间')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='最近发现对象时间')),
                ('last_error', models.TextField(blank=True, verbose_name='最近清理错误')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='管理员归档时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingVideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(verbose_name='分段序号')),
                ('duration_ms', models.PositiveIntegerField(verbose_name='分段时长毫秒')),
                ('size_bytes', models.PositiveBigIntegerField(verbose_name='分段大小')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('relative_path', models.CharField(blank=True, max_length=500, verbose_name='临时相对路径')),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('uploaded', '已上传'), ('deleted', '已删除'), ('failed', '失败')], default='uploading', max_length=20, verbose_name='状态')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='上传完成时间')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAssemblyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '处理中'), ('succeeded', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('output_relative_path', models.CharField(blank=True, max_length=500, verbose_name='输出相对路径')),
                ('qiniu_object_key', models.CharField(blank=True, max_length=500, verbose_name='七牛对象 Key')),
                ('qiniu_attempt_object_key', models.CharField(blank=True, max_length=500, verbose_name='七牛上传尝试对象 Key')),
                ('qiniu_object_hash', models.CharField(blank=True, max_length=120, verbose_name='七牛对象 Hash')),
                ('qiniu_upload_deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='七牛上传截止时间')),
                ('cleanup_status', models.CharField(choices=[('pending', '待清理'), ('succeeded', '清理成功'), ('failed', '清理失败')], default='pending', max_length=20, verbose_name='清理状态')),
                ('cleanup_attempt_count', models.PositiveIntegerField(default=0, verbose_name='清理尝试次数')),
                ('failure_reason', models.TextField(blank=True, verbose_name='失败原因')),
                ('cleanup_error', models.TextField(blank=True, verbose_name='清理失败原因')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='心跳时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='actual_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='实际时长'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='cleanup_attempt_count',
            field=models.PositiveIntegerField(default=0, verbose_name='解绑清理尝试次数'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='cleanup_error',
            field=models.TextField(blank=True, verbose_name='解绑清理失败原因'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='cleanup_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解绑清理心跳时间'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='cleanup_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='解绑清理请求时间'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='cleanup_status',
            field=models.CharField(blank=True, choices=[('', '无需清理'), ('pending', '待清理'), ('running', '清理中'), ('failed', '清理失败')], default='', max_length=20, verbose_name='解绑清理状态'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='expected_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='计划时长'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='expected_segment_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='计划分段数'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交完成时间'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='note',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='bucket',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='空间'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='object_key',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='对象 Key'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='project_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_video_uploads', to='studies.projectpatient'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='status',
            field=models.CharField(choices=[('recording', '录制中'), ('uploading_segments', '分段上传中'), ('queued', '等待合并'), ('assembling', '合并中'), ('uploading_qiniu', '上传七牛中'), ('attached', '已绑定'), ('failed', '失败'), ('expired', '已过期')], default='recording', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='uploaded_segment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='已上传分段数'),
        ),
        migrations.AddConstraint(
            model_name='motionanalysisjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('training_video',), name='unique_active_motion_analysis_job_per_video'),
        ),
        migrations.AddConstraint(
            model_name='trainingvideo',
            constraint=models.UniqueConstraint(fields=('project_patient', 'client_session_id'), name='unique_training_video_client_session_per_patient'),
        ),
        migrations.AddField(
            model_name='trainingvideosegment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingvideosegment',
            name='training_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='training.trainingvideo'),
        ),
        migrations.AddField(
            model_name='trainingvideosegment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoassemblyjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoassemblyjob',
            name='training_video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_job', to='training.trainingvideo'),
        ),
        migrations.AddField(
            model_name='videoassemblyjob',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='trainingvideosegment',
            constraint=models.UniqueConstraint(fields=('training_video', 'index'), name='unique_training_video_segment_index'),
        ),
    ]
