# Generated by Django 5.2.17 on 2026-09-05 07:00

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


def fail_active_motion_analysis_jobs(apps, schema_editor):
    MotionAnalysisJob = apps.get_model("training", "MotionAnalysisJob")
    MotionAnalysisJob.objects.filter(status__in=["pending", "running"]).update(
        status="failed",
        failure_code="service_migration",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0012_motion_action_video_object_keys'),
        ('studies', '0004_studyproject_completed_at'),
        ('training', '0013_trainingvideo_training_window'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='motionanalysisjob',
            name='action_source_key',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='动作来源键'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='completion_idempotency_key',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='完成幂等键'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='failure_code',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='失败代码'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近心跳时间'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='租约过期时间'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='lease_token_hash',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='租约令牌哈希'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='parameter_version',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='参数版本'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='skeleton_bucket',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='骨架空间'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='skeleton_duration_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='骨架时长'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='skeleton_fps',
            field=models.FloatField(blank=True, null=True, verbose_name='骨架帧率'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='skeleton_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='骨架高度'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='skeleton_object_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='骨架对象哈希'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='skeleton_object_key',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='骨架对象 Key'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='skeleton_size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='骨架大小'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='skeleton_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='骨架宽度'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='subject_tracker_version',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='受试者跟踪版本'),
        ),
        migrations.AddField(
            model_name='motionanalysisjob',
            name='worker_id',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='工作节点 ID'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='motion_nonstandard_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='非标准动作次数'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='motion_quality_data',
            field=models.JSONField(default=dict, verbose_name='动作质量数据'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='motion_result_source',
            field=models.CharField(blank=True, choices=[('algorithm', '算法'), ('doctor', '医生')], default='', max_length=20, verbose_name='动作结果来源'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='motion_result_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='动作结果更新时间'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='motion_result_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motion_results_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='motion_standard_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='标准动作次数'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='motion_total_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='动作总次数'),
        ),
        migrations.AddConstraint(
            model_name='trainingrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('motion_nonstandard_count__isnull', True), ('motion_standard_count__isnull', True), ('motion_total_count__isnull', True)), models.Q(('motion_nonstandard_count__isnull', False), ('motion_standard_count__isnull', False), ('motion_total_count', django.db.models.expressions.CombinedExpression(models.F('motion_standard_count'), '+', models.F('motion_nonstandard_count'))), ('motion_total_count__isnull', False)), _connector='OR'), name='training_record_motion_counts_consistent'),
        ),
        migrations.RunPython(
            fail_active_motion_analysis_jobs,
            migrations.RunPython.noop,
        ),
    ]
