# Generated by Django 5.2.17 on 2026-09-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0014_pp_mcare_control_plane"),
    ]

    operations = [
        migrations.AddField(
            model_name="motionanalysisjob",
            name="current_stage",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="当前阶段"),
        ),
    ]
