# Generated by Django 5.2.14 on 2026-09-09 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0017_backfill_game_question_results"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingDetailExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("patient_id_snapshot", models.PositiveBigIntegerField()),
                ("project_id_snapshot", models.PositiveBigIntegerField()),
                ("project_patient_id_snapshot", models.PositiveBigIntegerField()),
                ("filters", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "生成中"),
                            ("succeeded", "已生成"),
                            ("failed", "失败"),
                        ],
                        default="generating",
                        max_length=16,
                    ),
                ),
                ("format_version", models.CharField(default="training_detail_v1", max_length=32)),
                ("row_counts", models.JSONField(default=dict)),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "无"),
                            ("limit_exceeded", "超出容量"),
                            ("deadline_exceeded", "生成超时"),
                            ("generation_failed", "生成失败"),
                            ("audit_failed", "审计失败"),
                            ("scope_changed", "授权范围变化"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
