# Generated by Django 5.2.14 on 2026-09-09 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_training_detail_export_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestionresult',
            name='click_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='拼图点击次数'),
        ),
        migrations.AddField(
            model_name='gamequestionresult',
            name='expected_step_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='应选择步数'),
        ),
        migrations.AlterField(
            model_name='gamequestionresult',
            name='capture_version',
            field=models.CharField(choices=[('legacy_wall_clock_v0', '历史墙上时钟'), ('active_response_v1', '有效作答时间'), ('active_response_v2', '有效作答及逐步选择时间')], max_length=32, verbose_name='采集版本'),
        ),
        migrations.AlterField(
            model_name='gamequestionresult',
            name='result_type',
            field=models.CharField(choices=[('answered', '已作答'), ('timeout', '答题超时'), ('interrupted', '未完成')], max_length=20, verbose_name='结果类型'),
        ),
        migrations.AlterField(
            model_name='trainingdetailexportlog',
            name='format_version',
            field=models.CharField(default='training_detail_v2', max_length=32),
        ),
        migrations.CreateModel(
            name='GameQuestionSelectionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveIntegerField(verbose_name='选择序号')),
                ('selected_value', models.CharField(max_length=32, verbose_name='所选内容')),
                ('expected_value', models.CharField(max_length=32, verbose_name='正确内容')),
                ('response_duration_ms', models.PositiveIntegerField(verbose_name='有效选择耗时毫秒')),
                ('is_correct', models.BooleanField(verbose_name='是否正确')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_steps', to='training.gamequestionresult')),
            ],
            options={
                'ordering': ['step_index', 'id'],
                'constraints': [models.UniqueConstraint(fields=('question', 'step_index'), name='game_selection_question_index_uniq'), models.CheckConstraint(condition=models.Q(('step_index__gte', 1), ('step_index__lte', 5)), name='game_selection_index_range'), models.CheckConstraint(condition=models.Q(('response_duration_ms__gte', 0), ('response_duration_ms__lte', 3600000)), name='game_selection_duration_range')],
            },
        ),
    ]
