# Generated by Django 5.2.14 on 2026-09-14 14:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_studyproject_completed_at'),
        ('training', '0019_game_selection_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingUploadDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('client_session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('video_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('segment_index', models.PositiveIntegerField(blank=True, null=True)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('recording', '录制'), ('compression', '压缩'), ('file_read', '读取文件'), ('session', '创建会话'), ('status', '查询状态'), ('upload', '上传分片'), ('finalize', '提交完成')], max_length=16)),
                ('error_code', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=500)),
                ('network_type', models.CharField(max_length=32)),
                ('platform', models.CharField(max_length=32)),
                ('sdk_version', models.CharField(max_length=32)),
                ('app_version', models.CharField(max_length=32)),
                ('project_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_upload_diagnostics', to='studies.projectpatient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project_patient', 'event_id'), name='unique_upload_diagnostic_event_per_patient')],
            },
        ),
    ]
