# Generated by Django 5.2.14 on 2026-09-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0020_traininguploaddiagnostic"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingrecord",
            name="cutover_marker",
            field=models.UUIDField(blank=True, null=True, verbose_name="处方切换标记"),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="invalidated_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="作废时间"
            ),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="invalidation_reason",
            field=models.TextField(blank=True, verbose_name="作废原因"),
        ),
    ]
