# Generated by Django 5.2.14 on 2026-09-16 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescriptions", "0014_counted_motion_doses"),
        ("studies", "0004_studyproject_completed_at"),
        ("training", "0021_training_record_invalidation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotionSetAttempt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("abandoned_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="trainingvideo",
            name="motion_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="training.motionsetattempt",
            ),
        ),
        migrations.CreateModel(
            name="MotionTrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_session_id", models.UUIDField(unique=True)),
                ("planned_sets", models.PositiveIntegerField()),
                ("repetitions", models.PositiveIntegerField()),
                ("count_unit", models.CharField(max_length=16)),
                ("started_at", models.DateTimeField()),
                ("training_date", models.DateField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "prescription_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="prescriptions.prescriptionaction",
                    ),
                ),
                (
                    "project_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motion_sessions",
                        to="studies.projectpatient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MotionTrainingSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("index", models.PositiveIntegerField()),
                ("attempt_id", models.UUIDField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="training.motiontrainingsession",
                    ),
                ),
                (
                    "video",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_motion_set",
                        to="training.trainingvideo",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
        migrations.AddField(
            model_name="motionsetattempt",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="training.motiontrainingset",
            ),
        ),
        migrations.AddConstraint(
            model_name="motiontrainingset",
            constraint=models.UniqueConstraint(
                fields=("session", "index"), name="motion_session_set_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="motiontrainingset",
            constraint=models.CheckConstraint(
                condition=models.Q(("index__gt", 0)), name="motion_set_index_positive"
            ),
        ),
    ]
