# Generated by Django 5.2.14 on 2026-09-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_motion_training_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='motiontrainingset',
            name='completion_reason',
            field=models.CharField(choices=[('manual', '手动结束'), ('time_limit', '到时结束')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='direct_upload_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='直传凭证截止时间'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='upload_mode',
            field=models.CharField(choices=[('segments', '分片'), ('direct', '整文件直传')], default='segments', max_length=16, verbose_name='上传方式'),
        ),
    ]
