# Generated by Django 5.2.14 on 2026-05-08 10:39

from django.db import migrations, models


def normalize_patientbaseline_json_nulls(apps, schema_editor):
    PatientBaseline = apps.get_model("patients", "PatientBaseline")

    # Normalize NULL -> {} to avoid two "empty" semantics (NULL vs {}).
    PatientBaseline.objects.filter(demographics__isnull=True).update(demographics={})
    PatientBaseline.objects.filter(surgery_allergy__isnull=True).update(surgery_allergy={})
    PatientBaseline.objects.filter(comorbidities__isnull=True).update(comorbidities={})
    PatientBaseline.objects.filter(lifestyle__isnull=True).update(lifestyle={})
    PatientBaseline.objects.filter(baseline_medications__isnull=True).update(baseline_medications={})


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientbaseline'),
    ]

    operations = [
        migrations.RunPython(normalize_patientbaseline_json_nulls, reverse_code=noop_reverse),
        migrations.AlterField(
            model_name='patientbaseline',
            name='baseline_medications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='patientbaseline',
            name='comorbidities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='patientbaseline',
            name='demographics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='patientbaseline',
            name='lifestyle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='patientbaseline',
            name='name_initials',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='patientbaseline',
            name='surgery_allergy',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
