# Generated by Django 5.2.14 on 2026-05-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappbindingcode',
            name='code_hash',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='patientappbindingcode',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('used_at__isnull', True)), fields=('code_hash',), name='uniq_active_patient_app_binding_code_hash'),
        ),
    ]
