# Generated by Django 5.2.14 on 2026-08-30 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_legacy_session_openids(apps, schema_editor):
    PatientAppSession = apps.get_model("patient_app", "PatientAppSession")
    PatientAppSession.objects.exclude(wx_openid__isnull=True).update(wx_openid=None)


def restore_legacy_session_openids(apps, schema_editor):
    PatientAppSession = apps.get_model("patient_app", "PatientAppSession")
    PatientAppSession.objects.filter(wx_openid__isnull=True).update(wx_openid="")


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0002_alter_patientappbindingcode_code_hash'),
        ('studies', '0004_studyproject_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappsession',
            name='wx_openid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RunPython(
            clear_legacy_session_openids,
            restore_legacy_session_openids,
        ),
        migrations.CreateModel(
            name='PatientAppWechatBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wx_openid', models.CharField(max_length=128, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project_patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_app_wechat_binding', to='studies.projectpatient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
