# Generated by Django 5.2.16 on 2026-07-23 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_alter_patientbaseline_baseline_medications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WearableDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64, verbose_name='厂商')),
                ('external_device_id', models.CharField(max_length=128, verbose_name='厂商设备标识')),
                ('identifier_type', models.CharField(max_length=64, verbose_name='设备标识类型')),
                ('model', models.CharField(blank=True, max_length=128, verbose_name='设备型号')),
                ('short_code', models.CharField(max_length=4, unique=True, verbose_name='设备固定简码')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_communication_at', models.DateTimeField(blank=True, null=True, verbose_name='最近通信时间')),
                ('last_battery_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最近电量')),
                ('last_device_status', models.CharField(blank=True, max_length=32, verbose_name='最近设备状态')),
                ('last_status_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最近状态检查时间')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_device_id'), name='uniq_wearable_device_external_identity')],
            },
        ),
        migrations.CreateModel(
            name='WearableCommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command_type', models.CharField(max_length=64, verbose_name='命令类型')),
                ('command_code', models.CharField(blank=True, max_length=64, verbose_name='命令编码')),
                ('request_payload', models.JSONField(default=dict, verbose_name='请求参数')),
                ('provider_code', models.CharField(blank=True, max_length=64, verbose_name='厂商返回码')),
                ('status', models.CharField(choices=[('queued', '排队中'), ('succeeded', '成功'), ('offline', '设备离线'), ('timeout', '超时'), ('failed', '失败')], max_length=16, verbose_name='命令状态')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wearable_command_logs', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_logs', to='wearables.wearabledevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WearableBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bound_at', models.DateTimeField(verbose_name='绑定时间')),
                ('unbound_at', models.DateTimeField(blank=True, null=True, verbose_name='解绑时间')),
                ('unbind_reason', models.TextField(blank=True, verbose_name='解绑原因')),
                ('bound_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wearable_bindings_bound', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_bindings', to='patients.patient')),
                ('unbound_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wearable_bindings_unbound', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='wearables.wearabledevice')),
            ],
        ),
        migrations.CreateModel(
            name='WearableMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64, verbose_name='厂商')),
                ('metric_type', models.CharField(choices=[('heart_rate', '心率'), ('blood_pressure', '血压'), ('blood_oxygen', '血氧')], max_length=32, verbose_name='指标类型')),
                ('measured_at', models.DateTimeField(verbose_name='测量时间')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='心率')),
                ('systolic', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='收缩压')),
                ('diastolic', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='舒张压')),
                ('blood_oxygen', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='血氧')),
                ('source_fingerprint', models.CharField(max_length=64, verbose_name='来源指纹')),
                ('attribution_status', models.CharField(choices=[('attributed', '已归属'), ('outside_binding', '绑定区间外'), ('ambiguous', '归属不明确')], default='outside_binding', max_length=32, verbose_name='归属状态')),
                ('raw_payload', models.JSONField(default=dict, verbose_name='原始数据')),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='wearables.wearablebinding')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='wearables.wearabledevice')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wearable_measurements', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='WearableSyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.CharField(max_length=32, verbose_name='指标类型')),
                ('last_success_window_end', models.DateTimeField(blank=True, null=True, verbose_name='最近成功窗口结束时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_cursors', to='wearables.wearabledevice')),
            ],
        ),
        migrations.CreateModel(
            name='WearableSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.CharField(max_length=32, verbose_name='指标类型')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='计划时间')),
                ('window_start', models.DateTimeField(blank=True, null=True, verbose_name='同步窗口开始时间')),
                ('window_end', models.DateTimeField(blank=True, null=True, verbose_name='同步窗口结束时间')),
                ('status', models.CharField(choices=[('running', '运行中'), ('succeeded', '成功'), ('failed', '失败')], max_length=16, verbose_name='同步状态')),
                ('returned_count', models.PositiveIntegerField(default=0, verbose_name='返回数量')),
                ('error_code', models.CharField(blank=True, max_length=64, verbose_name='错误码')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='重试次数')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='wearables.wearabledevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WearableDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('heart_rate_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='平均心率')),
                ('heart_rate_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最低心率')),
                ('heart_rate_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最高心率')),
                ('heart_rate_count', models.PositiveIntegerField(default=0, verbose_name='心率测量次数')),
                ('systolic_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='平均收缩压')),
                ('diastolic_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='平均舒张压')),
                ('blood_pressure_count', models.PositiveIntegerField(default=0, verbose_name='血压测量次数')),
                ('blood_oxygen_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='平均血氧')),
                ('blood_oxygen_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最低血氧')),
                ('blood_oxygen_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最高血氧')),
                ('blood_oxygen_count', models.PositiveIntegerField(default=0, verbose_name='血氧测量次数')),
                ('steps', models.PositiveIntegerField(blank=True, null=True, verbose_name='步数')),
                ('steps_attribution_status', models.CharField(choices=[('attributed', '已归属'), ('outside_binding', '绑定区间外'), ('ambiguous', '归属不明确')], default='outside_binding', max_length=32, verbose_name='步数归属状态')),
                ('heart_rate_sync_status', models.CharField(choices=[('pending', '待同步'), ('succeeded', '同步成功'), ('failed', '同步失败')], default='pending', max_length=16, verbose_name='心率同步状态')),
                ('blood_pressure_sync_status', models.CharField(choices=[('pending', '待同步'), ('succeeded', '同步成功'), ('failed', '同步失败')], default='pending', max_length=16, verbose_name='血压同步状态')),
                ('blood_oxygen_sync_status', models.CharField(choices=[('pending', '待同步'), ('succeeded', '同步成功'), ('failed', '同步失败')], default='pending', max_length=16, verbose_name='血氧同步状态')),
                ('steps_sync_status', models.CharField(choices=[('pending', '待同步'), ('succeeded', '同步成功'), ('failed', '同步失败')], default='pending', max_length=16, verbose_name='步数同步状态')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='计算时间')),
                ('calculation_version', models.CharField(default='1', max_length=32, verbose_name='计算版本')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_daily_summaries', to='patients.patient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient', 'record_date'), name='uniq_wearable_daily_summary')],
            },
        ),
        migrations.CreateModel(
            name='WearableDailySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64, verbose_name='厂商')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('steps', models.PositiveIntegerField(blank=True, null=True, verbose_name='步数')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='距离')),
                ('calorie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='卡路里')),
                ('attribution_status', models.CharField(choices=[('attributed', '已归属'), ('outside_binding', '绑定区间外'), ('ambiguous', '归属不明确')], default='outside_binding', max_length=32, verbose_name='归属状态')),
                ('raw_payload', models.JSONField(default=dict, verbose_name='原始数据')),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_sources', to='wearables.wearablebinding')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wearable_daily_sources', to='patients.patient')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sources', to='wearables.wearabledevice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'device', 'record_date'), name='uniq_wearable_daily_source')],
            },
        ),
        migrations.AddConstraint(
            model_name='wearablebinding',
            constraint=models.UniqueConstraint(condition=models.Q(('unbound_at__isnull', True)), fields=('patient',), name='uniq_active_wearable_binding_per_patient'),
        ),
        migrations.AddConstraint(
            model_name='wearablebinding',
            constraint=models.UniqueConstraint(condition=models.Q(('unbound_at__isnull', True)), fields=('device',), name='uniq_active_wearable_binding_per_device'),
        ),
        migrations.AddConstraint(
            model_name='wearablebinding',
            constraint=models.CheckConstraint(condition=models.Q(('unbound_at__isnull', True), ('unbound_at__gt', models.F('bound_at')), _connector='OR'), name='wearable_binding_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='wearablemeasurement',
            constraint=models.UniqueConstraint(fields=('provider', 'device', 'metric_type', 'source_fingerprint'), name='uniq_wearable_measurement_source'),
        ),
        migrations.AddConstraint(
            model_name='wearablesynccursor',
            constraint=models.UniqueConstraint(fields=('device', 'metric_type'), name='uniq_wearable_sync_cursor'),
        ),
    ]
