# Generated by Django 5.2.16 on 2026-07-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearables', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wearabledevice',
            constraint=models.CheckConstraint(condition=models.Q(('short_code__regex', '^\\d{4}$')), name='wearable_device_short_code_four_digits'),
        ),
    ]
