# Generated by Django 5.2.16 on 2026-07-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearables', '0002_wearabledevice_wearable_device_short_code_four_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearablecommandlog',
            name='next_poll_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次轮询时间'),
        ),
        migrations.AddField(
            model_name='wearablecommandlog',
            name='poll_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='轮询次数'),
        ),
        migrations.AddField(
            model_name='wearablecommandlog',
            name='poll_deadline_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='轮询截止时间'),
        ),
        migrations.AddField(
            model_name='wearablecommandlog',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际发命令时间'),
        ),
    ]
