# Generated by Django 5.2.14 on 2026-05-07 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_type', models.CharField(choices=[('T0', 'T0 筛选/入组'), ('T1', 'T1 干预12周'), ('T2', 'T2 干预后36周随访')], max_length=8, verbose_name='访视类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='访视日期')),
                ('form_data', models.JSONField(default=dict, verbose_name='访视表单数据')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='studies.projectpatient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project_patient', 'visit_type')},
            },
        ),
    ]
