# Generated by Django 5.2.14 on 2026-05-07 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='动作名称')),
                ('training_type', models.CharField(max_length=80, verbose_name='训练类型')),
                ('internal_type', models.CharField(choices=[('video', '视频类'), ('game', '游戏互动类'), ('motion', '运动类')], max_length=20, verbose_name='内部类型')),
                ('action_type', models.CharField(max_length=80, verbose_name='动作类型')),
                ('execution_description', models.TextField(blank=True, verbose_name='执行描述')),
                ('key_points', models.TextField(blank=True, verbose_name='动作要点')),
                ('suggested_frequency', models.CharField(blank=True, max_length=80, verbose_name='建议频次')),
                ('suggested_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='建议时长')),
                ('suggested_sets', models.PositiveIntegerField(blank=True, null=True, verbose_name='建议组数')),
                ('default_difficulty', models.CharField(blank=True, max_length=40, verbose_name='默认难度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(verbose_name='版本号')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='开设时间')),
                ('effective_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效中'), ('pending', '待生效'), ('archived', '已归档'), ('terminated', '已终止')], default='draft', max_length=20, verbose_name='状态')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('project_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='studies.projectpatient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project_patient', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PrescriptionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_name_snapshot', models.CharField(max_length=120, verbose_name='动作名称快照')),
                ('training_type_snapshot', models.CharField(max_length=80, verbose_name='训练类型快照')),
                ('internal_type_snapshot', models.CharField(max_length=20, verbose_name='内部类型快照')),
                ('action_type_snapshot', models.CharField(max_length=80, verbose_name='动作类型快照')),
                ('execution_description_snapshot', models.TextField(blank=True, verbose_name='执行描述快照')),
                ('frequency', models.CharField(blank=True, max_length=80, verbose_name='频次')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='时长')),
                ('sets', models.PositiveIntegerField(blank=True, null=True, verbose_name='组数')),
                ('difficulty', models.CharField(blank=True, max_length=40, verbose_name='难度')),
                ('notes', models.TextField(blank=True, verbose_name='注意事项')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('action_library_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescriptions.actionlibraryitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='prescriptions.prescription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
