# Generated by Django 5.2.14 on 2026-05-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='project_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='studies.projectpatient'),
        ),
    ]
