# Generated by Django 5.2.14 on 2026-05-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_seed_motion_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归档时间'),
        ),
    ]
