# Generated by Django 5.2.14 on 2026-09-16 05:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescriptions", "0013_disable_high_knee_ai_supervision"),
        ("studies", "0004_studyproject_completed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MotionPrescriptionCutover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("marker", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("switched_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="prescription",
            name="migration_source",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="prescriptionaction",
            name="count_unit",
            field=models.CharField(
                choices=[("total", "每组"), ("per_side", "每侧")], default="total", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="prescriptionaction",
            name="dose_mode",
            field=models.CharField(
                choices=[("duration", "时长"), ("sets", "计数组")],
                default="duration",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionaction",
            name="migrated_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="migrated_actions",
                to="prescriptions.prescriptionaction",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionaction",
            name="repetitions",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prescriptionaction",
            name="sets",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="prescriptionaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("dose_mode", "duration"),
                    models.Q(
                        ("dose_mode", "sets"),
                        ("duration_minutes__isnull", True),
                        ("repetitions__gt", 0),
                        ("repetitions__isnull", False),
                        ("sets__gt", 0),
                        ("sets__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="prescription_counted_dose_valid",
            ),
        ),
        migrations.AddField(
            model_name="motionprescriptioncutover",
            name="project_patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="studies.projectpatient"
            ),
        ),
    ]
